version: '3.4'

services:
  nosql.data:
    container_name: distributed-lock-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
  
  redis.cache:
    container_name: distributed-lock-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - fileshare:/mnt/fileshare

  producer:
    container_name: distributed-lock-producer
    image: distributed-lock-producer
    build:
      context: Producer
      dockerfile: Dockerfile
    volumes:
      - fileshare:/mnt/fileshare
      
  consumer:
    container_name: distributed-lock-consumer
    image: distributed-lock-consumer
    build:
        context: Consumer
        dockerfile: Dockerfile
    depends_on:
        - nosql.data
        - redis.cache
    ports:
        - "5001:8081"

volumes:
  fileshare:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: c:/temp/docker/fileshare